name: crisis_map_natural
description: "A Flutter project de catástrofes en ciudad."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.5.0

  # Geolocalización
  geolocator: ^14.0.0

  # SVG
  flutter_svg: ^2.0.7

  # Mapa
  flutter_map: ^4.0.0
  latlong2: ^0.8.2   # alineado con flutter_map ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
