// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8r7bmVe5YheT6XgHXIHXwydF3jT7xzPA',
    appId: '1:115807413505:web:eac6ceaf1bce80cdb32700',
    messagingSenderId: '115807413505',
    projectId: 'natural-crisis-map-7eea4',
    authDomain: 'natural-crisis-map-7eea4.firebaseapp.com',
    storageBucket: 'natural-crisis-map-7eea4.firebasestorage.app',
    measurementId: 'G-7E400Z2LRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBenoNHW3nddqiLWweSe9L1ixdVu5-RhRo',
    appId: '1:115807413505:android:732362d2a2b72e8fb32700',
    messagingSenderId: '115807413505',
    projectId: 'natural-crisis-map-7eea4',
    storageBucket: 'natural-crisis-map-7eea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ZIzce16dJlp34pP1Xz3Y9YbDOsZb6eI',
    appId: '1:115807413505:ios:7c8628dac35a3f59b32700',
    messagingSenderId: '115807413505',
    projectId: 'natural-crisis-map-7eea4',
    storageBucket: 'natural-crisis-map-7eea4.firebasestorage.app',
    iosBundleId: 'com.example.crisisMapNatural',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ZIzce16dJlp34pP1Xz3Y9YbDOsZb6eI',
    appId: '1:115807413505:ios:7c8628dac35a3f59b32700',
    messagingSenderId: '115807413505',
    projectId: 'natural-crisis-map-7eea4',
    storageBucket: 'natural-crisis-map-7eea4.firebasestorage.app',
    iosBundleId: 'com.example.crisisMapNatural',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8r7bmVe5YheT6XgHXIHXwydF3jT7xzPA',
    appId: '1:115807413505:web:6562c2b6a7ebc5e1b32700',
    messagingSenderId: '115807413505',
    projectId: 'natural-crisis-map-7eea4',
    authDomain: 'natural-crisis-map-7eea4.firebaseapp.com',
    storageBucket: 'natural-crisis-map-7eea4.firebasestorage.app',
    measurementId: 'G-BNFJ3J0W4G',
  );
}
